### ISSUE TITLE
Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by daguar** [codeforgermany/click_that_hood#54]
One of the most recent commits (since last night) seems to have created an error for me. Will be investigating more later today, but here's what happens as of this commit:
https://github.com/codeforamerica/click_that_hood/commit/87772b71e813893e67719b47e26d27fa9d9a79d9

After cloning the repo, I did npm install and then:

➜  click_that_hood git:(master) ✗ node app.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/daguar/Documents/Code/cfa/cth-temp/click_that_hood/app.js:1:77)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)

**Comment by yesezra** [comment]
Run `npm install` to make sure you have all the dependencies, then try
again. Do you still have an error?
